RunCommandFirstJoin: "kits 新手礼包 %player%"
FirstJoinMessage: "&d欢迎新玩家 &c%player% &d来到夜之城!"
JoinMessage: "&e%player%&b加入了夜之城!"
JoinMessageVip: "&e%player%&c[VIP]&b加入了夜之城!"
JoinMessageSvip: "&e%player%&6[SVIP]&b加入了夜之城!"
QuitMessage: "&e%player%&b离开了夜之城!"
QuitMessageVip: "&e%player%&c[VIP]&b离开了夜之城!"
QuitMessageSvip: "&e%player%&6[SVIP]&b离开了夜之城!"
ProtectWorld: "world"
ProtectOre:
  - COAL_ORE
  - IRON_ORE
  - GOLD_ORE
  - LAPIS_ORE
  - DIAMOND_ORE
  - EMERALD_ORE
  - REDSTONE_ORE
  - COPPER_ORE
  - DEEPSLATE_COAL_ORE
  - DEEPSLATE_IRON_ORE
  - DEEPSLATE_GOLD_ORE
  - DEEPSLATE_LAPIS_ORE
  - DEEPSLATE_DIAMOND_ORE
  - DEEPSLATE_EMERALD_ORE
  - DEEPSLATE_RESSTONE_ORE
  - DEEPSLATE_COPPER_ORE
  - DEEPSLATE_REDSTONE_ORE
  - NETHER_GOLD_ORE
  - NETHER_QUARTZ_ORE
  - ANCIENT_DEBRIS

treasure:
  # 生成宝藏的世界
  world: "zy"
  # 生成宝藏的间隔(单位：秒)
  time: 600
  # 生成宝藏的几率
  random: 0.5
  # 最多可以生成宝藏数量
  max: 5
  # 生成范围(会生成负数)
  radius: 25000